run_logged $SMRTR_INSTALL/packaging/base.sh
run_logged $SMRTR_INSTALL/packaging/fonts.sh
run_logged $SMRTR_INSTALL/packaging/nvim.sh
run_logged $SMRTR_INSTALL/packaging/icons.sh
run_logged $SMRTR_INSTALL/packaging/webapps.sh
run_logged $SMRTR_INSTALL/packaging/tuis.sh
run_logged $SMRTR_INSTALL/packaging/asus-rog.sh
run_logged $SMRTR_INSTALL/packaging/framework16.sh
run_logged $SMRTR_INSTALL/packaging/surface.sh
