general {
    lock_cmd = lowr-lock-screen              # lock screen
    before_sleep_cmd = loginctl lock-session # lock before suspend
    after_sleep_cmd = brightnessctl -r       # restore brightness after sleep
    inhibit_sleep = 3                        # wait until screen is locked
}

listener {
    timeout = 150                                             # 2.5min
    on-timeout = pidof hyprlock || lowr-launch-screensaver # start screensaver (if we haven't locked already)
}

listener {
    timeout = 151                      # 5min
    on-timeout = loginctl lock-session # lock screen when timeout has passed
}

listener {
    timeout = 330                                            # 5.5min
    on-timeout = brightnessctl -sd '*::kbd_backlight' set 0  # save state and turn off keyboard backlight
    on-resume = brightnessctl -rd '*::kbd_backlight'         # restore keyboard backlight
}

listener {
    timeout = 330                         # 5.5min
    on-timeout = loginctl lock-session    # lock screen when timeout has passed
    on-resume = brightnessctl -r          # restore brightness when activity resumes
}
