onboarding = false

[keys]
focus_pane_left = ["prefix+h", "alt+t"]
focus_pane_right = ["prefix+l", "alt+r"]
focus_pane_up = ["prefix+k", "alt+m"]
focus_pane_down = ["prefix+j", "alt+n"]
split_horizontal = ["prefix+minus", "alt+comma"]
split_vertical = ["prefix+v", "alt+period"]
close_pane = ["prefix+x", "alt+j"]
switch_tab = ["prefix+1..9", "alt+1..9"]
next_tab = ["prefix+n", "alt+l"]
previous_tab = ["prefix+p", "alt+b"]
next_workspace = "alt+h"
previous_workspace = "alt+d"
new_tab = ["prefix+c", "alt+w"]
new_workspace = ["prefix+shift+n", "alt+g"]
close_tab = ["prefix+shift+x", "alt+shift+w"]
close_workspace = ["prefix+shift+d", "alt+shift+g"]

[ui]
agent_panel_sort = "priority"

show_agent_labels_on_pane_borders = false
[theme]
name = "gruvbox"
auto_switch = false

[ui.toast]
delivery = "system"

[terminal]
default_shell = "nu"

[experimental]
kitty_graphics = true
